version: '3.8'
services:
  frontend:
    build:
      context: ../Study_BuddAI_FE 
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../Study_BuddAI_BE  
      dockerfile: Dockerfile.prod  
    ports:
      - "8080:8080"
    env_file: .env.docker
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    # ports:  # Only uncomment if need external DB access
    #   - "3306:3306"

volumes:
  mysql-data: